/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class genomicsdb_GenomicsDBQueryStream */

#ifndef _Included_genomicsdb_GenomicsDBQueryStream
#define _Included_genomicsdb_GenomicsDBQueryStream
#ifdef __cplusplus
extern "C" {
#endif
#undef genomicsdb_GenomicsDBQueryStream_MAX_SKIP_BUFFER_SIZE
#define genomicsdb_GenomicsDBQueryStream_MAX_SKIP_BUFFER_SIZE 2048L
/*
 * Class:     genomicsdb_GenomicsDBQueryStream
 * Method:    jniGenomicsDBInit
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;IIIJJ)J
 */
JNIEXPORT jlong JNICALL Java_genomicsdb_GenomicsDBQueryStream_jniGenomicsDBInit
  (JNIEnv *, jobject, jstring, jstring, jstring, jint, jint, jint, jlong, jlong);

/*
 * Class:     genomicsdb_GenomicsDBQueryStream
 * Method:    jniGenomicsDBClose
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_genomicsdb_GenomicsDBQueryStream_jniGenomicsDBClose
  (JNIEnv *, jobject, jlong);

/*
 * Class:     genomicsdb_GenomicsDBQueryStream
 * Method:    jniGenomicsDBGetNumBytesAvailable
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_genomicsdb_GenomicsDBQueryStream_jniGenomicsDBGetNumBytesAvailable
  (JNIEnv *, jobject, jlong);

/*
 * Class:     genomicsdb_GenomicsDBQueryStream
 * Method:    jniGenomicsDBReadNextByte
 * Signature: (J)B
 */
JNIEXPORT jbyte JNICALL Java_genomicsdb_GenomicsDBQueryStream_jniGenomicsDBReadNextByte
  (JNIEnv *, jobject, jlong);

/*
 * Class:     genomicsdb_GenomicsDBQueryStream
 * Method:    jniGenomicsDBRead
 * Signature: (J[BII)I
 */
JNIEXPORT jint JNICALL Java_genomicsdb_GenomicsDBQueryStream_jniGenomicsDBRead
  (JNIEnv *, jobject, jlong, jbyteArray, jint, jint);

/*
 * Class:     genomicsdb_GenomicsDBQueryStream
 * Method:    jniGenomicsDBSkip
 * Signature: (JJ)J
 */
JNIEXPORT jlong JNICALL Java_genomicsdb_GenomicsDBQueryStream_jniGenomicsDBSkip
  (JNIEnv *, jobject, jlong, jlong);

#ifdef __cplusplus
}
#endif
#endif
