// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: genomicsdb_callsets_mapping.proto

package com.intel.genomicsdb;

public final class GenomicsDBCallsetsMapProto {
  private GenomicsDBCallsetsMapProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface SampleIDToTileDBIDMapOrBuilder extends
      // @@protoc_insertion_point(interface_extends:SampleIDToTileDBIDMap)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required string sample_name = 1;</code>
     */
    boolean hasSampleName();
    /**
     * <code>required string sample_name = 1;</code>
     */
    java.lang.String getSampleName();
    /**
     * <code>required string sample_name = 1;</code>
     */
    com.google.protobuf.ByteString
        getSampleNameBytes();

    /**
     * <code>required int64 tiledb_row_index = 2;</code>
     */
    boolean hasTiledbRowIndex();
    /**
     * <code>required int64 tiledb_row_index = 2;</code>
     */
    long getTiledbRowIndex();

    /**
     * <code>required int32 sample_vcf_index = 3;</code>
     */
    boolean hasSampleVcfIndex();
    /**
     * <code>required int32 sample_vcf_index = 3;</code>
     */
    int getSampleVcfIndex();

    /**
     * <code>optional string stream_name = 4;</code>
     */
    boolean hasStreamName();
    /**
     * <code>optional string stream_name = 4;</code>
     */
    java.lang.String getStreamName();
    /**
     * <code>optional string stream_name = 4;</code>
     */
    com.google.protobuf.ByteString
        getStreamNameBytes();
  }
  /**
   * Protobuf type {@code SampleIDToTileDBIDMap}
   */
  public  static final class SampleIDToTileDBIDMap extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:SampleIDToTileDBIDMap)
      SampleIDToTileDBIDMapOrBuilder {
    // Use SampleIDToTileDBIDMap.newBuilder() to construct.
    private SampleIDToTileDBIDMap(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private SampleIDToTileDBIDMap() {
      sampleName_ = "";
      tiledbRowIndex_ = 0L;
      sampleVcfIndex_ = 0;
      streamName_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private SampleIDToTileDBIDMap(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              sampleName_ = bs;
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              tiledbRowIndex_ = input.readInt64();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              sampleVcfIndex_ = input.readInt32();
              break;
            }
            case 34: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000008;
              streamName_ = bs;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.intel.genomicsdb.GenomicsDBCallsetsMapProto.internal_static_SampleIDToTileDBIDMap_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.intel.genomicsdb.GenomicsDBCallsetsMapProto.internal_static_SampleIDToTileDBIDMap_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.intel.genomicsdb.GenomicsDBCallsetsMapProto.SampleIDToTileDBIDMap.class, com.intel.genomicsdb.GenomicsDBCallsetsMapProto.SampleIDToTileDBIDMap.Builder.class);
    }

    private int bitField0_;
    public static final int SAMPLE_NAME_FIELD_NUMBER = 1;
    private volatile java.lang.Object sampleName_;
    /**
     * <code>required string sample_name = 1;</code>
     */
    public boolean hasSampleName() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string sample_name = 1;</code>
     */
    public java.lang.String getSampleName() {
      java.lang.Object ref = sampleName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          sampleName_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string sample_name = 1;</code>
     */
    public com.google.protobuf.ByteString
        getSampleNameBytes() {
      java.lang.Object ref = sampleName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        sampleName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TILEDB_ROW_INDEX_FIELD_NUMBER = 2;
    private long tiledbRowIndex_;
    /**
     * <code>required int64 tiledb_row_index = 2;</code>
     */
    public boolean hasTiledbRowIndex() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required int64 tiledb_row_index = 2;</code>
     */
    public long getTiledbRowIndex() {
      return tiledbRowIndex_;
    }

    public static final int SAMPLE_VCF_INDEX_FIELD_NUMBER = 3;
    private int sampleVcfIndex_;
    /**
     * <code>required int32 sample_vcf_index = 3;</code>
     */
    public boolean hasSampleVcfIndex() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required int32 sample_vcf_index = 3;</code>
     */
    public int getSampleVcfIndex() {
      return sampleVcfIndex_;
    }

    public static final int STREAM_NAME_FIELD_NUMBER = 4;
    private volatile java.lang.Object streamName_;
    /**
     * <code>optional string stream_name = 4;</code>
     */
    public boolean hasStreamName() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional string stream_name = 4;</code>
     */
    public java.lang.String getStreamName() {
      java.lang.Object ref = streamName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          streamName_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string stream_name = 4;</code>
     */
    public com.google.protobuf.ByteString
        getStreamNameBytes() {
      java.lang.Object ref = streamName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        streamName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasSampleName()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasTiledbRowIndex()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasSampleVcfIndex()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, sampleName_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt64(2, tiledbRowIndex_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt32(3, sampleVcfIndex_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, streamName_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, sampleName_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(2, tiledbRowIndex_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, sampleVcfIndex_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, streamName_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.intel.genomicsdb.GenomicsDBCallsetsMapProto.SampleIDToTileDBIDMap)) {
        return super.equals(obj);
      }
      com.intel.genomicsdb.GenomicsDBCallsetsMapProto.SampleIDToTileDBIDMap other = (com.intel.genomicsdb.GenomicsDBCallsetsMapProto.SampleIDToTileDBIDMap) obj;

      boolean result = true;
      result = result && (hasSampleName() == other.hasSampleName());
      if (hasSampleName()) {
        result = result && getSampleName()
            .equals(other.getSampleName());
      }
      result = result && (hasTiledbRowIndex() == other.hasTiledbRowIndex());
      if (hasTiledbRowIndex()) {
        result = result && (getTiledbRowIndex()
            == other.getTiledbRowIndex());
      }
      result = result && (hasSampleVcfIndex() == other.hasSampleVcfIndex());
      if (hasSampleVcfIndex()) {
        result = result && (getSampleVcfIndex()
            == other.getSampleVcfIndex());
      }
      result = result && (hasStreamName() == other.hasStreamName());
      if (hasStreamName()) {
        result = result && getStreamName()
            .equals(other.getStreamName());
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasSampleName()) {
        hash = (37 * hash) + SAMPLE_NAME_FIELD_NUMBER;
        hash = (53 * hash) + getSampleName().hashCode();
      }
      if (hasTiledbRowIndex()) {
        hash = (37 * hash) + TILEDB_ROW_INDEX_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            getTiledbRowIndex());
      }
      if (hasSampleVcfIndex()) {
        hash = (37 * hash) + SAMPLE_VCF_INDEX_FIELD_NUMBER;
        hash = (53 * hash) + getSampleVcfIndex();
      }
      if (hasStreamName()) {
        hash = (37 * hash) + STREAM_NAME_FIELD_NUMBER;
        hash = (53 * hash) + getStreamName().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.intel.genomicsdb.GenomicsDBCallsetsMapProto.SampleIDToTileDBIDMap parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.intel.genomicsdb.GenomicsDBCallsetsMapProto.SampleIDToTileDBIDMap parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.intel.genomicsdb.GenomicsDBCallsetsMapProto.SampleIDToTileDBIDMap parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.intel.genomicsdb.GenomicsDBCallsetsMapProto.SampleIDToTileDBIDMap parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.intel.genomicsdb.GenomicsDBCallsetsMapProto.SampleIDToTileDBIDMap parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.intel.genomicsdb.GenomicsDBCallsetsMapProto.SampleIDToTileDBIDMap parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.intel.genomicsdb.GenomicsDBCallsetsMapProto.SampleIDToTileDBIDMap parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.intel.genomicsdb.GenomicsDBCallsetsMapProto.SampleIDToTileDBIDMap parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.intel.genomicsdb.GenomicsDBCallsetsMapProto.SampleIDToTileDBIDMap parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.intel.genomicsdb.GenomicsDBCallsetsMapProto.SampleIDToTileDBIDMap parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.intel.genomicsdb.GenomicsDBCallsetsMapProto.SampleIDToTileDBIDMap prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code SampleIDToTileDBIDMap}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:SampleIDToTileDBIDMap)
        com.intel.genomicsdb.GenomicsDBCallsetsMapProto.SampleIDToTileDBIDMapOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.intel.genomicsdb.GenomicsDBCallsetsMapProto.internal_static_SampleIDToTileDBIDMap_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.intel.genomicsdb.GenomicsDBCallsetsMapProto.internal_static_SampleIDToTileDBIDMap_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.intel.genomicsdb.GenomicsDBCallsetsMapProto.SampleIDToTileDBIDMap.class, com.intel.genomicsdb.GenomicsDBCallsetsMapProto.SampleIDToTileDBIDMap.Builder.class);
      }

      // Construct using com.intel.genomicsdb.GenomicsDBCallsetsMapProto.SampleIDToTileDBIDMap.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        sampleName_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        tiledbRowIndex_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000002);
        sampleVcfIndex_ = 0;
        bitField0_ = (bitField0_ & ~0x00000004);
        streamName_ = "";
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.intel.genomicsdb.GenomicsDBCallsetsMapProto.internal_static_SampleIDToTileDBIDMap_descriptor;
      }

      public com.intel.genomicsdb.GenomicsDBCallsetsMapProto.SampleIDToTileDBIDMap getDefaultInstanceForType() {
        return com.intel.genomicsdb.GenomicsDBCallsetsMapProto.SampleIDToTileDBIDMap.getDefaultInstance();
      }

      public com.intel.genomicsdb.GenomicsDBCallsetsMapProto.SampleIDToTileDBIDMap build() {
        com.intel.genomicsdb.GenomicsDBCallsetsMapProto.SampleIDToTileDBIDMap result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.intel.genomicsdb.GenomicsDBCallsetsMapProto.SampleIDToTileDBIDMap buildPartial() {
        com.intel.genomicsdb.GenomicsDBCallsetsMapProto.SampleIDToTileDBIDMap result = new com.intel.genomicsdb.GenomicsDBCallsetsMapProto.SampleIDToTileDBIDMap(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.sampleName_ = sampleName_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.tiledbRowIndex_ = tiledbRowIndex_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.sampleVcfIndex_ = sampleVcfIndex_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.streamName_ = streamName_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.intel.genomicsdb.GenomicsDBCallsetsMapProto.SampleIDToTileDBIDMap) {
          return mergeFrom((com.intel.genomicsdb.GenomicsDBCallsetsMapProto.SampleIDToTileDBIDMap)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.intel.genomicsdb.GenomicsDBCallsetsMapProto.SampleIDToTileDBIDMap other) {
        if (other == com.intel.genomicsdb.GenomicsDBCallsetsMapProto.SampleIDToTileDBIDMap.getDefaultInstance()) return this;
        if (other.hasSampleName()) {
          bitField0_ |= 0x00000001;
          sampleName_ = other.sampleName_;
          onChanged();
        }
        if (other.hasTiledbRowIndex()) {
          setTiledbRowIndex(other.getTiledbRowIndex());
        }
        if (other.hasSampleVcfIndex()) {
          setSampleVcfIndex(other.getSampleVcfIndex());
        }
        if (other.hasStreamName()) {
          bitField0_ |= 0x00000008;
          streamName_ = other.streamName_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        if (!hasSampleName()) {
          return false;
        }
        if (!hasTiledbRowIndex()) {
          return false;
        }
        if (!hasSampleVcfIndex()) {
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.intel.genomicsdb.GenomicsDBCallsetsMapProto.SampleIDToTileDBIDMap parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.intel.genomicsdb.GenomicsDBCallsetsMapProto.SampleIDToTileDBIDMap) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object sampleName_ = "";
      /**
       * <code>required string sample_name = 1;</code>
       */
      public boolean hasSampleName() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string sample_name = 1;</code>
       */
      public java.lang.String getSampleName() {
        java.lang.Object ref = sampleName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            sampleName_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string sample_name = 1;</code>
       */
      public com.google.protobuf.ByteString
          getSampleNameBytes() {
        java.lang.Object ref = sampleName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          sampleName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string sample_name = 1;</code>
       */
      public Builder setSampleName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        sampleName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string sample_name = 1;</code>
       */
      public Builder clearSampleName() {
        bitField0_ = (bitField0_ & ~0x00000001);
        sampleName_ = getDefaultInstance().getSampleName();
        onChanged();
        return this;
      }
      /**
       * <code>required string sample_name = 1;</code>
       */
      public Builder setSampleNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        sampleName_ = value;
        onChanged();
        return this;
      }

      private long tiledbRowIndex_ ;
      /**
       * <code>required int64 tiledb_row_index = 2;</code>
       */
      public boolean hasTiledbRowIndex() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required int64 tiledb_row_index = 2;</code>
       */
      public long getTiledbRowIndex() {
        return tiledbRowIndex_;
      }
      /**
       * <code>required int64 tiledb_row_index = 2;</code>
       */
      public Builder setTiledbRowIndex(long value) {
        bitField0_ |= 0x00000002;
        tiledbRowIndex_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int64 tiledb_row_index = 2;</code>
       */
      public Builder clearTiledbRowIndex() {
        bitField0_ = (bitField0_ & ~0x00000002);
        tiledbRowIndex_ = 0L;
        onChanged();
        return this;
      }

      private int sampleVcfIndex_ ;
      /**
       * <code>required int32 sample_vcf_index = 3;</code>
       */
      public boolean hasSampleVcfIndex() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required int32 sample_vcf_index = 3;</code>
       */
      public int getSampleVcfIndex() {
        return sampleVcfIndex_;
      }
      /**
       * <code>required int32 sample_vcf_index = 3;</code>
       */
      public Builder setSampleVcfIndex(int value) {
        bitField0_ |= 0x00000004;
        sampleVcfIndex_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 sample_vcf_index = 3;</code>
       */
      public Builder clearSampleVcfIndex() {
        bitField0_ = (bitField0_ & ~0x00000004);
        sampleVcfIndex_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object streamName_ = "";
      /**
       * <code>optional string stream_name = 4;</code>
       */
      public boolean hasStreamName() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional string stream_name = 4;</code>
       */
      public java.lang.String getStreamName() {
        java.lang.Object ref = streamName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            streamName_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string stream_name = 4;</code>
       */
      public com.google.protobuf.ByteString
          getStreamNameBytes() {
        java.lang.Object ref = streamName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          streamName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string stream_name = 4;</code>
       */
      public Builder setStreamName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        streamName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string stream_name = 4;</code>
       */
      public Builder clearStreamName() {
        bitField0_ = (bitField0_ & ~0x00000008);
        streamName_ = getDefaultInstance().getStreamName();
        onChanged();
        return this;
      }
      /**
       * <code>optional string stream_name = 4;</code>
       */
      public Builder setStreamNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        streamName_ = value;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:SampleIDToTileDBIDMap)
    }

    // @@protoc_insertion_point(class_scope:SampleIDToTileDBIDMap)
    private static final com.intel.genomicsdb.GenomicsDBCallsetsMapProto.SampleIDToTileDBIDMap DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.intel.genomicsdb.GenomicsDBCallsetsMapProto.SampleIDToTileDBIDMap();
    }

    public static com.intel.genomicsdb.GenomicsDBCallsetsMapProto.SampleIDToTileDBIDMap getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<SampleIDToTileDBIDMap>
        PARSER = new com.google.protobuf.AbstractParser<SampleIDToTileDBIDMap>() {
      public SampleIDToTileDBIDMap parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new SampleIDToTileDBIDMap(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<SampleIDToTileDBIDMap> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<SampleIDToTileDBIDMap> getParserForType() {
      return PARSER;
    }

    public com.intel.genomicsdb.GenomicsDBCallsetsMapProto.SampleIDToTileDBIDMap getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface CallsetMapOrBuilder extends
      // @@protoc_insertion_point(interface_extends:CallsetMap)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .SampleIDToTileDBIDMap callset_map = 1;</code>
     */
    java.util.List<com.intel.genomicsdb.GenomicsDBCallsetsMapProto.SampleIDToTileDBIDMap> 
        getCallsetMapList();
    /**
     * <code>repeated .SampleIDToTileDBIDMap callset_map = 1;</code>
     */
    com.intel.genomicsdb.GenomicsDBCallsetsMapProto.SampleIDToTileDBIDMap getCallsetMap(int index);
    /**
     * <code>repeated .SampleIDToTileDBIDMap callset_map = 1;</code>
     */
    int getCallsetMapCount();
    /**
     * <code>repeated .SampleIDToTileDBIDMap callset_map = 1;</code>
     */
    java.util.List<? extends com.intel.genomicsdb.GenomicsDBCallsetsMapProto.SampleIDToTileDBIDMapOrBuilder> 
        getCallsetMapOrBuilderList();
    /**
     * <code>repeated .SampleIDToTileDBIDMap callset_map = 1;</code>
     */
    com.intel.genomicsdb.GenomicsDBCallsetsMapProto.SampleIDToTileDBIDMapOrBuilder getCallsetMapOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code CallsetMap}
   */
  public  static final class CallsetMap extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:CallsetMap)
      CallsetMapOrBuilder {
    // Use CallsetMap.newBuilder() to construct.
    private CallsetMap(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private CallsetMap() {
      callsetMap_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private CallsetMap(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                callsetMap_ = new java.util.ArrayList<com.intel.genomicsdb.GenomicsDBCallsetsMapProto.SampleIDToTileDBIDMap>();
                mutable_bitField0_ |= 0x00000001;
              }
              callsetMap_.add(
                  input.readMessage(com.intel.genomicsdb.GenomicsDBCallsetsMapProto.SampleIDToTileDBIDMap.PARSER, extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          callsetMap_ = java.util.Collections.unmodifiableList(callsetMap_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.intel.genomicsdb.GenomicsDBCallsetsMapProto.internal_static_CallsetMap_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.intel.genomicsdb.GenomicsDBCallsetsMapProto.internal_static_CallsetMap_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.intel.genomicsdb.GenomicsDBCallsetsMapProto.CallsetMap.class, com.intel.genomicsdb.GenomicsDBCallsetsMapProto.CallsetMap.Builder.class);
    }

    public static final int CALLSET_MAP_FIELD_NUMBER = 1;
    private java.util.List<com.intel.genomicsdb.GenomicsDBCallsetsMapProto.SampleIDToTileDBIDMap> callsetMap_;
    /**
     * <code>repeated .SampleIDToTileDBIDMap callset_map = 1;</code>
     */
    public java.util.List<com.intel.genomicsdb.GenomicsDBCallsetsMapProto.SampleIDToTileDBIDMap> getCallsetMapList() {
      return callsetMap_;
    }
    /**
     * <code>repeated .SampleIDToTileDBIDMap callset_map = 1;</code>
     */
    public java.util.List<? extends com.intel.genomicsdb.GenomicsDBCallsetsMapProto.SampleIDToTileDBIDMapOrBuilder> 
        getCallsetMapOrBuilderList() {
      return callsetMap_;
    }
    /**
     * <code>repeated .SampleIDToTileDBIDMap callset_map = 1;</code>
     */
    public int getCallsetMapCount() {
      return callsetMap_.size();
    }
    /**
     * <code>repeated .SampleIDToTileDBIDMap callset_map = 1;</code>
     */
    public com.intel.genomicsdb.GenomicsDBCallsetsMapProto.SampleIDToTileDBIDMap getCallsetMap(int index) {
      return callsetMap_.get(index);
    }
    /**
     * <code>repeated .SampleIDToTileDBIDMap callset_map = 1;</code>
     */
    public com.intel.genomicsdb.GenomicsDBCallsetsMapProto.SampleIDToTileDBIDMapOrBuilder getCallsetMapOrBuilder(
        int index) {
      return callsetMap_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      for (int i = 0; i < getCallsetMapCount(); i++) {
        if (!getCallsetMap(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < callsetMap_.size(); i++) {
        output.writeMessage(1, callsetMap_.get(i));
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < callsetMap_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, callsetMap_.get(i));
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.intel.genomicsdb.GenomicsDBCallsetsMapProto.CallsetMap)) {
        return super.equals(obj);
      }
      com.intel.genomicsdb.GenomicsDBCallsetsMapProto.CallsetMap other = (com.intel.genomicsdb.GenomicsDBCallsetsMapProto.CallsetMap) obj;

      boolean result = true;
      result = result && getCallsetMapList()
          .equals(other.getCallsetMapList());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (getCallsetMapCount() > 0) {
        hash = (37 * hash) + CALLSET_MAP_FIELD_NUMBER;
        hash = (53 * hash) + getCallsetMapList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.intel.genomicsdb.GenomicsDBCallsetsMapProto.CallsetMap parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.intel.genomicsdb.GenomicsDBCallsetsMapProto.CallsetMap parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.intel.genomicsdb.GenomicsDBCallsetsMapProto.CallsetMap parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.intel.genomicsdb.GenomicsDBCallsetsMapProto.CallsetMap parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.intel.genomicsdb.GenomicsDBCallsetsMapProto.CallsetMap parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.intel.genomicsdb.GenomicsDBCallsetsMapProto.CallsetMap parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.intel.genomicsdb.GenomicsDBCallsetsMapProto.CallsetMap parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.intel.genomicsdb.GenomicsDBCallsetsMapProto.CallsetMap parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.intel.genomicsdb.GenomicsDBCallsetsMapProto.CallsetMap parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.intel.genomicsdb.GenomicsDBCallsetsMapProto.CallsetMap parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.intel.genomicsdb.GenomicsDBCallsetsMapProto.CallsetMap prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code CallsetMap}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:CallsetMap)
        com.intel.genomicsdb.GenomicsDBCallsetsMapProto.CallsetMapOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.intel.genomicsdb.GenomicsDBCallsetsMapProto.internal_static_CallsetMap_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.intel.genomicsdb.GenomicsDBCallsetsMapProto.internal_static_CallsetMap_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.intel.genomicsdb.GenomicsDBCallsetsMapProto.CallsetMap.class, com.intel.genomicsdb.GenomicsDBCallsetsMapProto.CallsetMap.Builder.class);
      }

      // Construct using com.intel.genomicsdb.GenomicsDBCallsetsMapProto.CallsetMap.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getCallsetMapFieldBuilder();
        }
      }
      public Builder clear() {
        super.clear();
        if (callsetMapBuilder_ == null) {
          callsetMap_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          callsetMapBuilder_.clear();
        }
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.intel.genomicsdb.GenomicsDBCallsetsMapProto.internal_static_CallsetMap_descriptor;
      }

      public com.intel.genomicsdb.GenomicsDBCallsetsMapProto.CallsetMap getDefaultInstanceForType() {
        return com.intel.genomicsdb.GenomicsDBCallsetsMapProto.CallsetMap.getDefaultInstance();
      }

      public com.intel.genomicsdb.GenomicsDBCallsetsMapProto.CallsetMap build() {
        com.intel.genomicsdb.GenomicsDBCallsetsMapProto.CallsetMap result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.intel.genomicsdb.GenomicsDBCallsetsMapProto.CallsetMap buildPartial() {
        com.intel.genomicsdb.GenomicsDBCallsetsMapProto.CallsetMap result = new com.intel.genomicsdb.GenomicsDBCallsetsMapProto.CallsetMap(this);
        int from_bitField0_ = bitField0_;
        if (callsetMapBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001)) {
            callsetMap_ = java.util.Collections.unmodifiableList(callsetMap_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.callsetMap_ = callsetMap_;
        } else {
          result.callsetMap_ = callsetMapBuilder_.build();
        }
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.intel.genomicsdb.GenomicsDBCallsetsMapProto.CallsetMap) {
          return mergeFrom((com.intel.genomicsdb.GenomicsDBCallsetsMapProto.CallsetMap)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.intel.genomicsdb.GenomicsDBCallsetsMapProto.CallsetMap other) {
        if (other == com.intel.genomicsdb.GenomicsDBCallsetsMapProto.CallsetMap.getDefaultInstance()) return this;
        if (callsetMapBuilder_ == null) {
          if (!other.callsetMap_.isEmpty()) {
            if (callsetMap_.isEmpty()) {
              callsetMap_ = other.callsetMap_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureCallsetMapIsMutable();
              callsetMap_.addAll(other.callsetMap_);
            }
            onChanged();
          }
        } else {
          if (!other.callsetMap_.isEmpty()) {
            if (callsetMapBuilder_.isEmpty()) {
              callsetMapBuilder_.dispose();
              callsetMapBuilder_ = null;
              callsetMap_ = other.callsetMap_;
              bitField0_ = (bitField0_ & ~0x00000001);
              callsetMapBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getCallsetMapFieldBuilder() : null;
            } else {
              callsetMapBuilder_.addAllMessages(other.callsetMap_);
            }
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        for (int i = 0; i < getCallsetMapCount(); i++) {
          if (!getCallsetMap(i).isInitialized()) {
            return false;
          }
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.intel.genomicsdb.GenomicsDBCallsetsMapProto.CallsetMap parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.intel.genomicsdb.GenomicsDBCallsetsMapProto.CallsetMap) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.util.List<com.intel.genomicsdb.GenomicsDBCallsetsMapProto.SampleIDToTileDBIDMap> callsetMap_ =
        java.util.Collections.emptyList();
      private void ensureCallsetMapIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          callsetMap_ = new java.util.ArrayList<com.intel.genomicsdb.GenomicsDBCallsetsMapProto.SampleIDToTileDBIDMap>(callsetMap_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.intel.genomicsdb.GenomicsDBCallsetsMapProto.SampleIDToTileDBIDMap, com.intel.genomicsdb.GenomicsDBCallsetsMapProto.SampleIDToTileDBIDMap.Builder, com.intel.genomicsdb.GenomicsDBCallsetsMapProto.SampleIDToTileDBIDMapOrBuilder> callsetMapBuilder_;

      /**
       * <code>repeated .SampleIDToTileDBIDMap callset_map = 1;</code>
       */
      public java.util.List<com.intel.genomicsdb.GenomicsDBCallsetsMapProto.SampleIDToTileDBIDMap> getCallsetMapList() {
        if (callsetMapBuilder_ == null) {
          return java.util.Collections.unmodifiableList(callsetMap_);
        } else {
          return callsetMapBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .SampleIDToTileDBIDMap callset_map = 1;</code>
       */
      public int getCallsetMapCount() {
        if (callsetMapBuilder_ == null) {
          return callsetMap_.size();
        } else {
          return callsetMapBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .SampleIDToTileDBIDMap callset_map = 1;</code>
       */
      public com.intel.genomicsdb.GenomicsDBCallsetsMapProto.SampleIDToTileDBIDMap getCallsetMap(int index) {
        if (callsetMapBuilder_ == null) {
          return callsetMap_.get(index);
        } else {
          return callsetMapBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .SampleIDToTileDBIDMap callset_map = 1;</code>
       */
      public Builder setCallsetMap(
          int index, com.intel.genomicsdb.GenomicsDBCallsetsMapProto.SampleIDToTileDBIDMap value) {
        if (callsetMapBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureCallsetMapIsMutable();
          callsetMap_.set(index, value);
          onChanged();
        } else {
          callsetMapBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .SampleIDToTileDBIDMap callset_map = 1;</code>
       */
      public Builder setCallsetMap(
          int index, com.intel.genomicsdb.GenomicsDBCallsetsMapProto.SampleIDToTileDBIDMap.Builder builderForValue) {
        if (callsetMapBuilder_ == null) {
          ensureCallsetMapIsMutable();
          callsetMap_.set(index, builderForValue.build());
          onChanged();
        } else {
          callsetMapBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .SampleIDToTileDBIDMap callset_map = 1;</code>
       */
      public Builder addCallsetMap(com.intel.genomicsdb.GenomicsDBCallsetsMapProto.SampleIDToTileDBIDMap value) {
        if (callsetMapBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureCallsetMapIsMutable();
          callsetMap_.add(value);
          onChanged();
        } else {
          callsetMapBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .SampleIDToTileDBIDMap callset_map = 1;</code>
       */
      public Builder addCallsetMap(
          int index, com.intel.genomicsdb.GenomicsDBCallsetsMapProto.SampleIDToTileDBIDMap value) {
        if (callsetMapBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureCallsetMapIsMutable();
          callsetMap_.add(index, value);
          onChanged();
        } else {
          callsetMapBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .SampleIDToTileDBIDMap callset_map = 1;</code>
       */
      public Builder addCallsetMap(
          com.intel.genomicsdb.GenomicsDBCallsetsMapProto.SampleIDToTileDBIDMap.Builder builderForValue) {
        if (callsetMapBuilder_ == null) {
          ensureCallsetMapIsMutable();
          callsetMap_.add(builderForValue.build());
          onChanged();
        } else {
          callsetMapBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .SampleIDToTileDBIDMap callset_map = 1;</code>
       */
      public Builder addCallsetMap(
          int index, com.intel.genomicsdb.GenomicsDBCallsetsMapProto.SampleIDToTileDBIDMap.Builder builderForValue) {
        if (callsetMapBuilder_ == null) {
          ensureCallsetMapIsMutable();
          callsetMap_.add(index, builderForValue.build());
          onChanged();
        } else {
          callsetMapBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .SampleIDToTileDBIDMap callset_map = 1;</code>
       */
      public Builder addAllCallsetMap(
          java.lang.Iterable<? extends com.intel.genomicsdb.GenomicsDBCallsetsMapProto.SampleIDToTileDBIDMap> values) {
        if (callsetMapBuilder_ == null) {
          ensureCallsetMapIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, callsetMap_);
          onChanged();
        } else {
          callsetMapBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .SampleIDToTileDBIDMap callset_map = 1;</code>
       */
      public Builder clearCallsetMap() {
        if (callsetMapBuilder_ == null) {
          callsetMap_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          callsetMapBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .SampleIDToTileDBIDMap callset_map = 1;</code>
       */
      public Builder removeCallsetMap(int index) {
        if (callsetMapBuilder_ == null) {
          ensureCallsetMapIsMutable();
          callsetMap_.remove(index);
          onChanged();
        } else {
          callsetMapBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .SampleIDToTileDBIDMap callset_map = 1;</code>
       */
      public com.intel.genomicsdb.GenomicsDBCallsetsMapProto.SampleIDToTileDBIDMap.Builder getCallsetMapBuilder(
          int index) {
        return getCallsetMapFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .SampleIDToTileDBIDMap callset_map = 1;</code>
       */
      public com.intel.genomicsdb.GenomicsDBCallsetsMapProto.SampleIDToTileDBIDMapOrBuilder getCallsetMapOrBuilder(
          int index) {
        if (callsetMapBuilder_ == null) {
          return callsetMap_.get(index);  } else {
          return callsetMapBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .SampleIDToTileDBIDMap callset_map = 1;</code>
       */
      public java.util.List<? extends com.intel.genomicsdb.GenomicsDBCallsetsMapProto.SampleIDToTileDBIDMapOrBuilder> 
           getCallsetMapOrBuilderList() {
        if (callsetMapBuilder_ != null) {
          return callsetMapBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(callsetMap_);
        }
      }
      /**
       * <code>repeated .SampleIDToTileDBIDMap callset_map = 1;</code>
       */
      public com.intel.genomicsdb.GenomicsDBCallsetsMapProto.SampleIDToTileDBIDMap.Builder addCallsetMapBuilder() {
        return getCallsetMapFieldBuilder().addBuilder(
            com.intel.genomicsdb.GenomicsDBCallsetsMapProto.SampleIDToTileDBIDMap.getDefaultInstance());
      }
      /**
       * <code>repeated .SampleIDToTileDBIDMap callset_map = 1;</code>
       */
      public com.intel.genomicsdb.GenomicsDBCallsetsMapProto.SampleIDToTileDBIDMap.Builder addCallsetMapBuilder(
          int index) {
        return getCallsetMapFieldBuilder().addBuilder(
            index, com.intel.genomicsdb.GenomicsDBCallsetsMapProto.SampleIDToTileDBIDMap.getDefaultInstance());
      }
      /**
       * <code>repeated .SampleIDToTileDBIDMap callset_map = 1;</code>
       */
      public java.util.List<com.intel.genomicsdb.GenomicsDBCallsetsMapProto.SampleIDToTileDBIDMap.Builder> 
           getCallsetMapBuilderList() {
        return getCallsetMapFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.intel.genomicsdb.GenomicsDBCallsetsMapProto.SampleIDToTileDBIDMap, com.intel.genomicsdb.GenomicsDBCallsetsMapProto.SampleIDToTileDBIDMap.Builder, com.intel.genomicsdb.GenomicsDBCallsetsMapProto.SampleIDToTileDBIDMapOrBuilder> 
          getCallsetMapFieldBuilder() {
        if (callsetMapBuilder_ == null) {
          callsetMapBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              com.intel.genomicsdb.GenomicsDBCallsetsMapProto.SampleIDToTileDBIDMap, com.intel.genomicsdb.GenomicsDBCallsetsMapProto.SampleIDToTileDBIDMap.Builder, com.intel.genomicsdb.GenomicsDBCallsetsMapProto.SampleIDToTileDBIDMapOrBuilder>(
                  callsetMap_,
                  ((bitField0_ & 0x00000001) == 0x00000001),
                  getParentForChildren(),
                  isClean());
          callsetMap_ = null;
        }
        return callsetMapBuilder_;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:CallsetMap)
    }

    // @@protoc_insertion_point(class_scope:CallsetMap)
    private static final com.intel.genomicsdb.GenomicsDBCallsetsMapProto.CallsetMap DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.intel.genomicsdb.GenomicsDBCallsetsMapProto.CallsetMap();
    }

    public static com.intel.genomicsdb.GenomicsDBCallsetsMapProto.CallsetMap getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<CallsetMap>
        PARSER = new com.google.protobuf.AbstractParser<CallsetMap>() {
      public CallsetMap parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new CallsetMap(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<CallsetMap> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<CallsetMap> getParserForType() {
      return PARSER;
    }

    public com.intel.genomicsdb.GenomicsDBCallsetsMapProto.CallsetMap getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_SampleIDToTileDBIDMap_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_SampleIDToTileDBIDMap_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_CallsetMap_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_CallsetMap_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n!genomicsdb_callsets_mapping.proto\"u\n\025S" +
      "ampleIDToTileDBIDMap\022\023\n\013sample_name\030\001 \002(" +
      "\t\022\030\n\020tiledb_row_index\030\002 \002(\003\022\030\n\020sample_vc" +
      "f_index\030\003 \002(\005\022\023\n\013stream_name\030\004 \001(\t\"9\n\nCa" +
      "llsetMap\022+\n\013callset_map\030\001 \003(\0132\026.SampleID" +
      "ToTileDBIDMapB2\n\024com.intel.genomicsdbB\032G" +
      "enomicsDBCallsetsMapProto"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_SampleIDToTileDBIDMap_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_SampleIDToTileDBIDMap_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_SampleIDToTileDBIDMap_descriptor,
        new java.lang.String[] { "SampleName", "TiledbRowIndex", "SampleVcfIndex", "StreamName", });
    internal_static_CallsetMap_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_CallsetMap_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_CallsetMap_descriptor,
        new java.lang.String[] { "CallsetMap", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
