// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: genomicsdb_callsets_mapping.proto

package com.intel.genomicsdb;

public final class GenomicsDBCallsetsMapProto {
  private GenomicsDBCallsetsMapProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface SampleIDToTileDBIDMapOrBuilder extends
      // @@protoc_insertion_point(interface_extends:SampleIDToTileDBIDMap)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required string sample_name = 1;</code>
     */
    boolean hasSampleName();
    /**
     * <code>required string sample_name = 1;</code>
     */
    java.lang.String getSampleName();
    /**
     * <code>required string sample_name = 1;</code>
     */
    com.google.protobuf.ByteString
        getSampleNameBytes();

    /**
     * <code>required int64 tiledb_row_index = 2;</code>
     */
    boolean hasTiledbRowIndex();
    /**
     * <code>required int64 tiledb_row_index = 2;</code>
     */
    long getTiledbRowIndex();

    /**
     * <code>required int32 idx_in_file = 3;</code>
     */
    boolean hasIdxInFile();
    /**
     * <code>required int32 idx_in_file = 3;</code>
     */
    int getIdxInFile();

    /**
     * <code>optional string stream_name = 4;</code>
     */
    boolean hasStreamName();
    /**
     * <code>optional string stream_name = 4;</code>
     */
    java.lang.String getStreamName();
    /**
     * <code>optional string stream_name = 4;</code>
     */
    com.google.protobuf.ByteString
        getStreamNameBytes();
  }
  /**
   * Protobuf type {@code SampleIDToTileDBIDMap}
   */
  public  static final class SampleIDToTileDBIDMap extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:SampleIDToTileDBIDMap)
      SampleIDToTileDBIDMapOrBuilder {
    // Use SampleIDToTileDBIDMap.newBuilder() to construct.
    private SampleIDToTileDBIDMap(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private SampleIDToTileDBIDMap() {
      sampleName_ = "";
      tiledbRowIndex_ = 0L;
      idxInFile_ = 0;
      streamName_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private SampleIDToTileDBIDMap(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              sampleName_ = bs;
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              tiledbRowIndex_ = input.readInt64();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              idxInFile_ = input.readInt32();
              break;
            }
            case 34: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000008;
              streamName_ = bs;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.intel.genomicsdb.GenomicsDBCallsetsMapProto.internal_static_SampleIDToTileDBIDMap_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.intel.genomicsdb.GenomicsDBCallsetsMapProto.internal_static_SampleIDToTileDBIDMap_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.intel.genomicsdb.GenomicsDBCallsetsMapProto.SampleIDToTileDBIDMap.class, com.intel.genomicsdb.GenomicsDBCallsetsMapProto.SampleIDToTileDBIDMap.Builder.class);
    }

    private int bitField0_;
    public static final int SAMPLE_NAME_FIELD_NUMBER = 1;
    private volatile java.lang.Object sampleName_;
    /**
     * <code>required string sample_name = 1;</code>
     */
    public boolean hasSampleName() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string sample_name = 1;</code>
     */
    public java.lang.String getSampleName() {
      java.lang.Object ref = sampleName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          sampleName_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string sample_name = 1;</code>
     */
    public com.google.protobuf.ByteString
        getSampleNameBytes() {
      java.lang.Object ref = sampleName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        sampleName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TILEDB_ROW_INDEX_FIELD_NUMBER = 2;
    private long tiledbRowIndex_;
    /**
     * <code>required int64 tiledb_row_index = 2;</code>
     */
    public boolean hasTiledbRowIndex() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required int64 tiledb_row_index = 2;</code>
     */
    public long getTiledbRowIndex() {
      return tiledbRowIndex_;
    }

    public static final int IDX_IN_FILE_FIELD_NUMBER = 3;
    private int idxInFile_;
    /**
     * <code>required int32 idx_in_file = 3;</code>
     */
    public boolean hasIdxInFile() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required int32 idx_in_file = 3;</code>
     */
    public int getIdxInFile() {
      return idxInFile_;
    }

    public static final int STREAM_NAME_FIELD_NUMBER = 4;
    private volatile java.lang.Object streamName_;
    /**
     * <code>optional string stream_name = 4;</code>
     */
    public boolean hasStreamName() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional string stream_name = 4;</code>
     */
    public java.lang.String getStreamName() {
      java.lang.Object ref = streamName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          streamName_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string stream_name = 4;</code>
     */
    public com.google.protobuf.ByteString
        getStreamNameBytes() {
      java.lang.Object ref = streamName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        streamName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasSampleName()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasTiledbRowIndex()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasIdxInFile()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, sampleName_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt64(2, tiledbRowIndex_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt32(3, idxInFile_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, streamName_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, sampleName_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(2, tiledbRowIndex_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, idxInFile_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, streamName_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.intel.genomicsdb.GenomicsDBCallsetsMapProto.SampleIDToTileDBIDMap)) {
        return super.equals(obj);
      }
      com.intel.genomicsdb.GenomicsDBCallsetsMapProto.SampleIDToTileDBIDMap other = (com.intel.genomicsdb.GenomicsDBCallsetsMapProto.SampleIDToTileDBIDMap) obj;

      boolean result = true;
      result = result && (hasSampleName() == other.hasSampleName());
      if (hasSampleName()) {
        result = result && getSampleName()
            .equals(other.getSampleName());
      }
      result = result && (hasTiledbRowIndex() == other.hasTiledbRowIndex());
      if (hasTiledbRowIndex()) {
        result = result && (getTiledbRowIndex()
            == other.getTiledbRowIndex());
      }
      result = result && (hasIdxInFile() == other.hasIdxInFile());
      if (hasIdxInFile()) {
        result = result && (getIdxInFile()
            == other.getIdxInFile());
      }
      result = result && (hasStreamName() == other.hasStreamName());
      if (hasStreamName()) {
        result = result && getStreamName()
            .equals(other.getStreamName());
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      if (hasSampleName()) {
        hash = (37 * hash) + SAMPLE_NAME_FIELD_NUMBER;
        hash = (53 * hash) + getSampleName().hashCode();
      }
      if (hasTiledbRowIndex()) {
        hash = (37 * hash) + TILEDB_ROW_INDEX_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            getTiledbRowIndex());
      }
      if (hasIdxInFile()) {
        hash = (37 * hash) + IDX_IN_FILE_FIELD_NUMBER;
        hash = (53 * hash) + getIdxInFile();
      }
      if (hasStreamName()) {
        hash = (37 * hash) + STREAM_NAME_FIELD_NUMBER;
        hash = (53 * hash) + getStreamName().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.intel.genomicsdb.GenomicsDBCallsetsMapProto.SampleIDToTileDBIDMap parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.intel.genomicsdb.GenomicsDBCallsetsMapProto.SampleIDToTileDBIDMap parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.intel.genomicsdb.GenomicsDBCallsetsMapProto.SampleIDToTileDBIDMap parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.intel.genomicsdb.GenomicsDBCallsetsMapProto.SampleIDToTileDBIDMap parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.intel.genomicsdb.GenomicsDBCallsetsMapProto.SampleIDToTileDBIDMap parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.intel.genomicsdb.GenomicsDBCallsetsMapProto.SampleIDToTileDBIDMap parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.intel.genomicsdb.GenomicsDBCallsetsMapProto.SampleIDToTileDBIDMap parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.intel.genomicsdb.GenomicsDBCallsetsMapProto.SampleIDToTileDBIDMap parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.intel.genomicsdb.GenomicsDBCallsetsMapProto.SampleIDToTileDBIDMap parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.intel.genomicsdb.GenomicsDBCallsetsMapProto.SampleIDToTileDBIDMap parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.intel.genomicsdb.GenomicsDBCallsetsMapProto.SampleIDToTileDBIDMap prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code SampleIDToTileDBIDMap}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:SampleIDToTileDBIDMap)
        com.intel.genomicsdb.GenomicsDBCallsetsMapProto.SampleIDToTileDBIDMapOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.intel.genomicsdb.GenomicsDBCallsetsMapProto.internal_static_SampleIDToTileDBIDMap_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.intel.genomicsdb.GenomicsDBCallsetsMapProto.internal_static_SampleIDToTileDBIDMap_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.intel.genomicsdb.GenomicsDBCallsetsMapProto.SampleIDToTileDBIDMap.class, com.intel.genomicsdb.GenomicsDBCallsetsMapProto.SampleIDToTileDBIDMap.Builder.class);
      }

      // Construct using com.intel.genomicsdb.GenomicsDBCallsetsMapProto.SampleIDToTileDBIDMap.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        sampleName_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        tiledbRowIndex_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000002);
        idxInFile_ = 0;
        bitField0_ = (bitField0_ & ~0x00000004);
        streamName_ = "";
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.intel.genomicsdb.GenomicsDBCallsetsMapProto.internal_static_SampleIDToTileDBIDMap_descriptor;
      }

      public com.intel.genomicsdb.GenomicsDBCallsetsMapProto.SampleIDToTileDBIDMap getDefaultInstanceForType() {
        return com.intel.genomicsdb.GenomicsDBCallsetsMapProto.SampleIDToTileDBIDMap.getDefaultInstance();
      }

      public com.intel.genomicsdb.GenomicsDBCallsetsMapProto.SampleIDToTileDBIDMap build() {
        com.intel.genomicsdb.GenomicsDBCallsetsMapProto.SampleIDToTileDBIDMap result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.intel.genomicsdb.GenomicsDBCallsetsMapProto.SampleIDToTileDBIDMap buildPartial() {
        com.intel.genomicsdb.GenomicsDBCallsetsMapProto.SampleIDToTileDBIDMap result = new com.intel.genomicsdb.GenomicsDBCallsetsMapProto.SampleIDToTileDBIDMap(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.sampleName_ = sampleName_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.tiledbRowIndex_ = tiledbRowIndex_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.idxInFile_ = idxInFile_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.streamName_ = streamName_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.intel.genomicsdb.GenomicsDBCallsetsMapProto.SampleIDToTileDBIDMap) {
          return mergeFrom((com.intel.genomicsdb.GenomicsDBCallsetsMapProto.SampleIDToTileDBIDMap)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.intel.genomicsdb.GenomicsDBCallsetsMapProto.SampleIDToTileDBIDMap other) {
        if (other == com.intel.genomicsdb.GenomicsDBCallsetsMapProto.SampleIDToTileDBIDMap.getDefaultInstance()) return this;
        if (other.hasSampleName()) {
          bitField0_ |= 0x00000001;
          sampleName_ = other.sampleName_;
          onChanged();
        }
        if (other.hasTiledbRowIndex()) {
          setTiledbRowIndex(other.getTiledbRowIndex());
        }
        if (other.hasIdxInFile()) {
          setIdxInFile(other.getIdxInFile());
        }
        if (other.hasStreamName()) {
          bitField0_ |= 0x00000008;
          streamName_ = other.streamName_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        if (!hasSampleName()) {
          return false;
        }
        if (!hasTiledbRowIndex()) {
          return false;
        }
        if (!hasIdxInFile()) {
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.intel.genomicsdb.GenomicsDBCallsetsMapProto.SampleIDToTileDBIDMap parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.intel.genomicsdb.GenomicsDBCallsetsMapProto.SampleIDToTileDBIDMap) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object sampleName_ = "";
      /**
       * <code>required string sample_name = 1;</code>
       */
      public boolean hasSampleName() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string sample_name = 1;</code>
       */
      public java.lang.String getSampleName() {
        java.lang.Object ref = sampleName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            sampleName_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string sample_name = 1;</code>
       */
      public com.google.protobuf.ByteString
          getSampleNameBytes() {
        java.lang.Object ref = sampleName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          sampleName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string sample_name = 1;</code>
       */
      public Builder setSampleName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        sampleName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string sample_name = 1;</code>
       */
      public Builder clearSampleName() {
        bitField0_ = (bitField0_ & ~0x00000001);
        sampleName_ = getDefaultInstance().getSampleName();
        onChanged();
        return this;
      }
      /**
       * <code>required string sample_name = 1;</code>
       */
      public Builder setSampleNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        sampleName_ = value;
        onChanged();
        return this;
      }

      private long tiledbRowIndex_ ;
      /**
       * <code>required int64 tiledb_row_index = 2;</code>
       */
      public boolean hasTiledbRowIndex() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required int64 tiledb_row_index = 2;</code>
       */
      public long getTiledbRowIndex() {
        return tiledbRowIndex_;
      }
      /**
       * <code>required int64 tiledb_row_index = 2;</code>
       */
      public Builder setTiledbRowIndex(long value) {
        bitField0_ |= 0x00000002;
        tiledbRowIndex_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int64 tiledb_row_index = 2;</code>
       */
      public Builder clearTiledbRowIndex() {
        bitField0_ = (bitField0_ & ~0x00000002);
        tiledbRowIndex_ = 0L;
        onChanged();
        return this;
      }

      private int idxInFile_ ;
      /**
       * <code>required int32 idx_in_file = 3;</code>
       */
      public boolean hasIdxInFile() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required int32 idx_in_file = 3;</code>
       */
      public int getIdxInFile() {
        return idxInFile_;
      }
      /**
       * <code>required int32 idx_in_file = 3;</code>
       */
      public Builder setIdxInFile(int value) {
        bitField0_ |= 0x00000004;
        idxInFile_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 idx_in_file = 3;</code>
       */
      public Builder clearIdxInFile() {
        bitField0_ = (bitField0_ & ~0x00000004);
        idxInFile_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object streamName_ = "";
      /**
       * <code>optional string stream_name = 4;</code>
       */
      public boolean hasStreamName() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional string stream_name = 4;</code>
       */
      public java.lang.String getStreamName() {
        java.lang.Object ref = streamName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            streamName_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string stream_name = 4;</code>
       */
      public com.google.protobuf.ByteString
          getStreamNameBytes() {
        java.lang.Object ref = streamName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          streamName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string stream_name = 4;</code>
       */
      public Builder setStreamName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        streamName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string stream_name = 4;</code>
       */
      public Builder clearStreamName() {
        bitField0_ = (bitField0_ & ~0x00000008);
        streamName_ = getDefaultInstance().getStreamName();
        onChanged();
        return this;
      }
      /**
       * <code>optional string stream_name = 4;</code>
       */
      public Builder setStreamNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        streamName_ = value;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:SampleIDToTileDBIDMap)
    }

    // @@protoc_insertion_point(class_scope:SampleIDToTileDBIDMap)
    private static final com.intel.genomicsdb.GenomicsDBCallsetsMapProto.SampleIDToTileDBIDMap DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.intel.genomicsdb.GenomicsDBCallsetsMapProto.SampleIDToTileDBIDMap();
    }

    public static com.intel.genomicsdb.GenomicsDBCallsetsMapProto.SampleIDToTileDBIDMap getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<SampleIDToTileDBIDMap>
        PARSER = new com.google.protobuf.AbstractParser<SampleIDToTileDBIDMap>() {
      public SampleIDToTileDBIDMap parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new SampleIDToTileDBIDMap(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<SampleIDToTileDBIDMap> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<SampleIDToTileDBIDMap> getParserForType() {
      return PARSER;
    }

    public com.intel.genomicsdb.GenomicsDBCallsetsMapProto.SampleIDToTileDBIDMap getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface CallsetMappingPBOrBuilder extends
      // @@protoc_insertion_point(interface_extends:CallsetMappingPB)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>map&lt;string, .SampleIDToTileDBIDMap&gt; callset_map = 1;</code>
     */
    int getCallsetMapCount();
    /**
     * <code>map&lt;string, .SampleIDToTileDBIDMap&gt; callset_map = 1;</code>
     */
    boolean containsCallsetMap(
        java.lang.String key);
    /**
     * Use {@link #getCallsetMapMap()} instead.
     */
    @java.lang.Deprecated
    java.util.Map<java.lang.String, com.intel.genomicsdb.GenomicsDBCallsetsMapProto.SampleIDToTileDBIDMap>
    getCallsetMap();
    /**
     * <code>map&lt;string, .SampleIDToTileDBIDMap&gt; callset_map = 1;</code>
     */
    java.util.Map<java.lang.String, com.intel.genomicsdb.GenomicsDBCallsetsMapProto.SampleIDToTileDBIDMap>
    getCallsetMapMap();
    /**
     * <code>map&lt;string, .SampleIDToTileDBIDMap&gt; callset_map = 1;</code>
     */

    com.intel.genomicsdb.GenomicsDBCallsetsMapProto.SampleIDToTileDBIDMap getCallsetMapOrDefault(
        java.lang.String key,
        com.intel.genomicsdb.GenomicsDBCallsetsMapProto.SampleIDToTileDBIDMap defaultValue);
    /**
     * <code>map&lt;string, .SampleIDToTileDBIDMap&gt; callset_map = 1;</code>
     */

    com.intel.genomicsdb.GenomicsDBCallsetsMapProto.SampleIDToTileDBIDMap getCallsetMapOrThrow(
        java.lang.String key);
  }
  /**
   * Protobuf type {@code CallsetMappingPB}
   */
  public  static final class CallsetMappingPB extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:CallsetMappingPB)
      CallsetMappingPBOrBuilder {
    // Use CallsetMappingPB.newBuilder() to construct.
    private CallsetMappingPB(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private CallsetMappingPB() {
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private CallsetMappingPB(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                callsetMap_ = com.google.protobuf.MapField.newMapField(
                    CallsetMapDefaultEntryHolder.defaultEntry);
                mutable_bitField0_ |= 0x00000001;
              }
              com.google.protobuf.MapEntry<java.lang.String, com.intel.genomicsdb.GenomicsDBCallsetsMapProto.SampleIDToTileDBIDMap>
              callsetMap = input.readMessage(
                  CallsetMapDefaultEntryHolder.defaultEntry.getParserForType(), extensionRegistry);
              callsetMap_.getMutableMap().put(callsetMap.getKey(), callsetMap.getValue());
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.intel.genomicsdb.GenomicsDBCallsetsMapProto.internal_static_CallsetMappingPB_descriptor;
    }

    @SuppressWarnings({"rawtypes"})
    protected com.google.protobuf.MapField internalGetMapField(
        int number) {
      switch (number) {
        case 1:
          return internalGetCallsetMap();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.intel.genomicsdb.GenomicsDBCallsetsMapProto.internal_static_CallsetMappingPB_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.intel.genomicsdb.GenomicsDBCallsetsMapProto.CallsetMappingPB.class, com.intel.genomicsdb.GenomicsDBCallsetsMapProto.CallsetMappingPB.Builder.class);
    }

    public static final int CALLSET_MAP_FIELD_NUMBER = 1;
    private static final class CallsetMapDefaultEntryHolder {
      static final com.google.protobuf.MapEntry<
          java.lang.String, com.intel.genomicsdb.GenomicsDBCallsetsMapProto.SampleIDToTileDBIDMap> defaultEntry =
              com.google.protobuf.MapEntry
              .<java.lang.String, com.intel.genomicsdb.GenomicsDBCallsetsMapProto.SampleIDToTileDBIDMap>newDefaultInstance(
                  com.intel.genomicsdb.GenomicsDBCallsetsMapProto.internal_static_CallsetMappingPB_CallsetMapEntry_descriptor, 
                  com.google.protobuf.WireFormat.FieldType.STRING,
                  "",
                  com.google.protobuf.WireFormat.FieldType.MESSAGE,
                  com.intel.genomicsdb.GenomicsDBCallsetsMapProto.SampleIDToTileDBIDMap.getDefaultInstance());
    }
    private com.google.protobuf.MapField<
        java.lang.String, com.intel.genomicsdb.GenomicsDBCallsetsMapProto.SampleIDToTileDBIDMap> callsetMap_;
    private com.google.protobuf.MapField<java.lang.String, com.intel.genomicsdb.GenomicsDBCallsetsMapProto.SampleIDToTileDBIDMap>
    internalGetCallsetMap() {
      if (callsetMap_ == null) {
        return com.google.protobuf.MapField.emptyMapField(
            CallsetMapDefaultEntryHolder.defaultEntry);
      }
      return callsetMap_;
    }

    public int getCallsetMapCount() {
      return internalGetCallsetMap().getMap().size();
    }
    /**
     * <code>map&lt;string, .SampleIDToTileDBIDMap&gt; callset_map = 1;</code>
     */

    public boolean containsCallsetMap(
        java.lang.String key) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      return internalGetCallsetMap().getMap().containsKey(key);
    }
    /**
     * Use {@link #getCallsetMapMap()} instead.
     */
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, com.intel.genomicsdb.GenomicsDBCallsetsMapProto.SampleIDToTileDBIDMap> getCallsetMap() {
      return getCallsetMapMap();
    }
    /**
     * <code>map&lt;string, .SampleIDToTileDBIDMap&gt; callset_map = 1;</code>
     */

    public java.util.Map<java.lang.String, com.intel.genomicsdb.GenomicsDBCallsetsMapProto.SampleIDToTileDBIDMap> getCallsetMapMap() {
      return internalGetCallsetMap().getMap();
    }
    /**
     * <code>map&lt;string, .SampleIDToTileDBIDMap&gt; callset_map = 1;</code>
     */

    public com.intel.genomicsdb.GenomicsDBCallsetsMapProto.SampleIDToTileDBIDMap getCallsetMapOrDefault(
        java.lang.String key,
        com.intel.genomicsdb.GenomicsDBCallsetsMapProto.SampleIDToTileDBIDMap defaultValue) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      java.util.Map<java.lang.String, com.intel.genomicsdb.GenomicsDBCallsetsMapProto.SampleIDToTileDBIDMap> map =
          internalGetCallsetMap().getMap();
      return map.containsKey(key) ? map.get(key) : defaultValue;
    }
    /**
     * <code>map&lt;string, .SampleIDToTileDBIDMap&gt; callset_map = 1;</code>
     */

    public com.intel.genomicsdb.GenomicsDBCallsetsMapProto.SampleIDToTileDBIDMap getCallsetMapOrThrow(
        java.lang.String key) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      java.util.Map<java.lang.String, com.intel.genomicsdb.GenomicsDBCallsetsMapProto.SampleIDToTileDBIDMap> map =
          internalGetCallsetMap().getMap();
      if (!map.containsKey(key)) {
        throw new java.lang.IllegalArgumentException();
      }
      return map.get(key);
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      for (com.intel.genomicsdb.GenomicsDBCallsetsMapProto.SampleIDToTileDBIDMap item : getCallsetMap().values()) {
        if (!item.isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (java.util.Map.Entry<java.lang.String, com.intel.genomicsdb.GenomicsDBCallsetsMapProto.SampleIDToTileDBIDMap> entry
           : internalGetCallsetMap().getMap().entrySet()) {
        com.google.protobuf.MapEntry<java.lang.String, com.intel.genomicsdb.GenomicsDBCallsetsMapProto.SampleIDToTileDBIDMap>
        callsetMap = CallsetMapDefaultEntryHolder.defaultEntry.newBuilderForType()
            .setKey(entry.getKey())
            .setValue(entry.getValue())
            .build();
        output.writeMessage(1, callsetMap);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      for (java.util.Map.Entry<java.lang.String, com.intel.genomicsdb.GenomicsDBCallsetsMapProto.SampleIDToTileDBIDMap> entry
           : internalGetCallsetMap().getMap().entrySet()) {
        com.google.protobuf.MapEntry<java.lang.String, com.intel.genomicsdb.GenomicsDBCallsetsMapProto.SampleIDToTileDBIDMap>
        callsetMap = CallsetMapDefaultEntryHolder.defaultEntry.newBuilderForType()
            .setKey(entry.getKey())
            .setValue(entry.getValue())
            .build();
        size += com.google.protobuf.CodedOutputStream
            .computeMessageSize(1, callsetMap);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.intel.genomicsdb.GenomicsDBCallsetsMapProto.CallsetMappingPB)) {
        return super.equals(obj);
      }
      com.intel.genomicsdb.GenomicsDBCallsetsMapProto.CallsetMappingPB other = (com.intel.genomicsdb.GenomicsDBCallsetsMapProto.CallsetMappingPB) obj;

      boolean result = true;
      result = result && internalGetCallsetMap().equals(
          other.internalGetCallsetMap());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      if (!internalGetCallsetMap().getMap().isEmpty()) {
        hash = (37 * hash) + CALLSET_MAP_FIELD_NUMBER;
        hash = (53 * hash) + internalGetCallsetMap().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.intel.genomicsdb.GenomicsDBCallsetsMapProto.CallsetMappingPB parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.intel.genomicsdb.GenomicsDBCallsetsMapProto.CallsetMappingPB parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.intel.genomicsdb.GenomicsDBCallsetsMapProto.CallsetMappingPB parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.intel.genomicsdb.GenomicsDBCallsetsMapProto.CallsetMappingPB parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.intel.genomicsdb.GenomicsDBCallsetsMapProto.CallsetMappingPB parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.intel.genomicsdb.GenomicsDBCallsetsMapProto.CallsetMappingPB parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.intel.genomicsdb.GenomicsDBCallsetsMapProto.CallsetMappingPB parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.intel.genomicsdb.GenomicsDBCallsetsMapProto.CallsetMappingPB parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.intel.genomicsdb.GenomicsDBCallsetsMapProto.CallsetMappingPB parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.intel.genomicsdb.GenomicsDBCallsetsMapProto.CallsetMappingPB parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.intel.genomicsdb.GenomicsDBCallsetsMapProto.CallsetMappingPB prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code CallsetMappingPB}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:CallsetMappingPB)
        com.intel.genomicsdb.GenomicsDBCallsetsMapProto.CallsetMappingPBOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.intel.genomicsdb.GenomicsDBCallsetsMapProto.internal_static_CallsetMappingPB_descriptor;
      }

      @SuppressWarnings({"rawtypes"})
      protected com.google.protobuf.MapField internalGetMapField(
          int number) {
        switch (number) {
          case 1:
            return internalGetCallsetMap();
          default:
            throw new RuntimeException(
                "Invalid map field number: " + number);
        }
      }
      @SuppressWarnings({"rawtypes"})
      protected com.google.protobuf.MapField internalGetMutableMapField(
          int number) {
        switch (number) {
          case 1:
            return internalGetMutableCallsetMap();
          default:
            throw new RuntimeException(
                "Invalid map field number: " + number);
        }
      }
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.intel.genomicsdb.GenomicsDBCallsetsMapProto.internal_static_CallsetMappingPB_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.intel.genomicsdb.GenomicsDBCallsetsMapProto.CallsetMappingPB.class, com.intel.genomicsdb.GenomicsDBCallsetsMapProto.CallsetMappingPB.Builder.class);
      }

      // Construct using com.intel.genomicsdb.GenomicsDBCallsetsMapProto.CallsetMappingPB.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        internalGetMutableCallsetMap().clear();
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.intel.genomicsdb.GenomicsDBCallsetsMapProto.internal_static_CallsetMappingPB_descriptor;
      }

      public com.intel.genomicsdb.GenomicsDBCallsetsMapProto.CallsetMappingPB getDefaultInstanceForType() {
        return com.intel.genomicsdb.GenomicsDBCallsetsMapProto.CallsetMappingPB.getDefaultInstance();
      }

      public com.intel.genomicsdb.GenomicsDBCallsetsMapProto.CallsetMappingPB build() {
        com.intel.genomicsdb.GenomicsDBCallsetsMapProto.CallsetMappingPB result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.intel.genomicsdb.GenomicsDBCallsetsMapProto.CallsetMappingPB buildPartial() {
        com.intel.genomicsdb.GenomicsDBCallsetsMapProto.CallsetMappingPB result = new com.intel.genomicsdb.GenomicsDBCallsetsMapProto.CallsetMappingPB(this);
        int from_bitField0_ = bitField0_;
        result.callsetMap_ = internalGetCallsetMap();
        result.callsetMap_.makeImmutable();
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.intel.genomicsdb.GenomicsDBCallsetsMapProto.CallsetMappingPB) {
          return mergeFrom((com.intel.genomicsdb.GenomicsDBCallsetsMapProto.CallsetMappingPB)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.intel.genomicsdb.GenomicsDBCallsetsMapProto.CallsetMappingPB other) {
        if (other == com.intel.genomicsdb.GenomicsDBCallsetsMapProto.CallsetMappingPB.getDefaultInstance()) return this;
        internalGetMutableCallsetMap().mergeFrom(
            other.internalGetCallsetMap());
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        for (com.intel.genomicsdb.GenomicsDBCallsetsMapProto.SampleIDToTileDBIDMap item : getCallsetMap().values()) {
          if (!item.isInitialized()) {
            return false;
          }
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.intel.genomicsdb.GenomicsDBCallsetsMapProto.CallsetMappingPB parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.intel.genomicsdb.GenomicsDBCallsetsMapProto.CallsetMappingPB) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private com.google.protobuf.MapField<
          java.lang.String, com.intel.genomicsdb.GenomicsDBCallsetsMapProto.SampleIDToTileDBIDMap> callsetMap_;
      private com.google.protobuf.MapField<java.lang.String, com.intel.genomicsdb.GenomicsDBCallsetsMapProto.SampleIDToTileDBIDMap>
      internalGetCallsetMap() {
        if (callsetMap_ == null) {
          return com.google.protobuf.MapField.emptyMapField(
              CallsetMapDefaultEntryHolder.defaultEntry);
        }
        return callsetMap_;
      }
      private com.google.protobuf.MapField<java.lang.String, com.intel.genomicsdb.GenomicsDBCallsetsMapProto.SampleIDToTileDBIDMap>
      internalGetMutableCallsetMap() {
        onChanged();;
        if (callsetMap_ == null) {
          callsetMap_ = com.google.protobuf.MapField.newMapField(
              CallsetMapDefaultEntryHolder.defaultEntry);
        }
        if (!callsetMap_.isMutable()) {
          callsetMap_ = callsetMap_.copy();
        }
        return callsetMap_;
      }

      public int getCallsetMapCount() {
        return internalGetCallsetMap().getMap().size();
      }
      /**
       * <code>map&lt;string, .SampleIDToTileDBIDMap&gt; callset_map = 1;</code>
       */

      public boolean containsCallsetMap(
          java.lang.String key) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        return internalGetCallsetMap().getMap().containsKey(key);
      }
      /**
       * Use {@link #getCallsetMapMap()} instead.
       */
      @java.lang.Deprecated
      public java.util.Map<java.lang.String, com.intel.genomicsdb.GenomicsDBCallsetsMapProto.SampleIDToTileDBIDMap> getCallsetMap() {
        return getCallsetMapMap();
      }
      /**
       * <code>map&lt;string, .SampleIDToTileDBIDMap&gt; callset_map = 1;</code>
       */

      public java.util.Map<java.lang.String, com.intel.genomicsdb.GenomicsDBCallsetsMapProto.SampleIDToTileDBIDMap> getCallsetMapMap() {
        return internalGetCallsetMap().getMap();
      }
      /**
       * <code>map&lt;string, .SampleIDToTileDBIDMap&gt; callset_map = 1;</code>
       */

      public com.intel.genomicsdb.GenomicsDBCallsetsMapProto.SampleIDToTileDBIDMap getCallsetMapOrDefault(
          java.lang.String key,
          com.intel.genomicsdb.GenomicsDBCallsetsMapProto.SampleIDToTileDBIDMap defaultValue) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        java.util.Map<java.lang.String, com.intel.genomicsdb.GenomicsDBCallsetsMapProto.SampleIDToTileDBIDMap> map =
            internalGetCallsetMap().getMap();
        return map.containsKey(key) ? map.get(key) : defaultValue;
      }
      /**
       * <code>map&lt;string, .SampleIDToTileDBIDMap&gt; callset_map = 1;</code>
       */

      public com.intel.genomicsdb.GenomicsDBCallsetsMapProto.SampleIDToTileDBIDMap getCallsetMapOrThrow(
          java.lang.String key) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        java.util.Map<java.lang.String, com.intel.genomicsdb.GenomicsDBCallsetsMapProto.SampleIDToTileDBIDMap> map =
            internalGetCallsetMap().getMap();
        if (!map.containsKey(key)) {
          throw new java.lang.IllegalArgumentException();
        }
        return map.get(key);
      }

      public Builder clearCallsetMap() {
        getMutableCallsetMap().clear();
        return this;
      }
      /**
       * <code>map&lt;string, .SampleIDToTileDBIDMap&gt; callset_map = 1;</code>
       */

      public Builder removeCallsetMap(
          java.lang.String key) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        getMutableCallsetMap().remove(key);
        return this;
      }
      /**
       * Use alternate mutation accessors instead.
       */
      @java.lang.Deprecated
      public java.util.Map<java.lang.String, com.intel.genomicsdb.GenomicsDBCallsetsMapProto.SampleIDToTileDBIDMap>
      getMutableCallsetMap() {
        return internalGetMutableCallsetMap().getMutableMap();
      }
      /**
       * <code>map&lt;string, .SampleIDToTileDBIDMap&gt; callset_map = 1;</code>
       */
      public Builder putCallsetMap(
          java.lang.String key,
          com.intel.genomicsdb.GenomicsDBCallsetsMapProto.SampleIDToTileDBIDMap value) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        if (value == null) { throw new java.lang.NullPointerException(); }
        getMutableCallsetMap().put(key, value);
        return this;
      }
      /**
       * <code>map&lt;string, .SampleIDToTileDBIDMap&gt; callset_map = 1;</code>
       */

      public Builder putAllCallsetMap(
          java.util.Map<java.lang.String, com.intel.genomicsdb.GenomicsDBCallsetsMapProto.SampleIDToTileDBIDMap> values) {
        getMutableCallsetMap().putAll(values);
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:CallsetMappingPB)
    }

    // @@protoc_insertion_point(class_scope:CallsetMappingPB)
    private static final com.intel.genomicsdb.GenomicsDBCallsetsMapProto.CallsetMappingPB DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.intel.genomicsdb.GenomicsDBCallsetsMapProto.CallsetMappingPB();
    }

    public static com.intel.genomicsdb.GenomicsDBCallsetsMapProto.CallsetMappingPB getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<CallsetMappingPB>
        PARSER = new com.google.protobuf.AbstractParser<CallsetMappingPB>() {
      public CallsetMappingPB parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new CallsetMappingPB(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<CallsetMappingPB> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<CallsetMappingPB> getParserForType() {
      return PARSER;
    }

    public com.intel.genomicsdb.GenomicsDBCallsetsMapProto.CallsetMappingPB getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_SampleIDToTileDBIDMap_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_SampleIDToTileDBIDMap_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_CallsetMappingPB_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_CallsetMappingPB_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_CallsetMappingPB_CallsetMapEntry_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_CallsetMappingPB_CallsetMapEntry_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n!genomicsdb_callsets_mapping.proto\"p\n\025S" +
      "ampleIDToTileDBIDMap\022\023\n\013sample_name\030\001 \002(" +
      "\t\022\030\n\020tiledb_row_index\030\002 \002(\003\022\023\n\013idx_in_fi" +
      "le\030\003 \002(\005\022\023\n\013stream_name\030\004 \001(\t\"\225\001\n\020Callse" +
      "tMappingPB\0226\n\013callset_map\030\001 \003(\0132!.Callse" +
      "tMappingPB.CallsetMapEntry\032I\n\017CallsetMap" +
      "Entry\022\013\n\003key\030\001 \001(\t\022%\n\005value\030\002 \001(\0132\026.Samp" +
      "leIDToTileDBIDMap:\0028\001B2\n\024com.intel.genom" +
      "icsdbB\032GenomicsDBCallsetsMapProto"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_SampleIDToTileDBIDMap_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_SampleIDToTileDBIDMap_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_SampleIDToTileDBIDMap_descriptor,
        new java.lang.String[] { "SampleName", "TiledbRowIndex", "IdxInFile", "StreamName", });
    internal_static_CallsetMappingPB_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_CallsetMappingPB_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_CallsetMappingPB_descriptor,
        new java.lang.String[] { "CallsetMap", });
    internal_static_CallsetMappingPB_CallsetMapEntry_descriptor =
      internal_static_CallsetMappingPB_descriptor.getNestedTypes().get(0);
    internal_static_CallsetMappingPB_CallsetMapEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_CallsetMappingPB_CallsetMapEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
